## DATA STRUCTURES 

Algorithms need necessary in-memory data structures that can hold temporary data while executing. Choosing the right data structures is essential for their efficient implementation.

    *Exploring data structures in Python
    *Exploring abstract data type
    *Stacks and queues
    *Trees
    
### Exploring Data Structures

    *Lists: Ordered mutable sequences of elements.
    *Tuples: Ordered immutable sequences of elements.
    *Sets: Unordered bags of elements.
    *Dictonary: Unordered bags of key-value pairs.
    *Data Frames:Two-dimensional structure to store two-dimensional data.

## LIST

In [17]:
#List
alist = ["Jhon","Toronto",33,True]
print(alist)
#List indexing
colors = ['Red','Green','Blue','Yellow']
print(colors)
print('Indexing of the list :',colors[1])
#List Slicing
print('Slicing of the list :',colors[0:2])
print('Slicing of the list :',colors[:2])
print('Slicing of the list :',colors[2:])
#Negative Slicing
print('Slicing of the list :',colors[:-1])
print('Slicing of the list :',colors[-2:-1])
#Nesting 
a = [1,2,[100,200,300],3]
print(max(a[2]))
#Iteration
for acolors in colors:
    print(acolors + " Square")

['Jhon', 'Toronto', 33, True]
['Red', 'Green', 'Blue', 'Yellow']
Indexing of the list : Green
Slicing of the list : ['Red', 'Green']
Slicing of the list : ['Red', 'Green']
Slicing of the list : ['Blue', 'Yellow']
Slicing of the list : ['Red', 'Green', 'Blue']
Slicing of the list : ['Blue']
300
Red Square
Green Square
Blue Square
Yellow Square


## Lambda Fuction in list

In [29]:
#Filtering Data
list(filter (lambda x: x > 100, [-5,200,300,-10,10,1000]))

[200, 300, 1000]

In [30]:
#Data Transformation
list(map(lambda x: x**2, [11,22,33,44,55]))

[121, 484, 1089, 1936, 3025]

In [34]:
#Data Aggregation
from functools import reduce
def dosum(x1,x2):
    return x1+x2
x = reduce(dosum,[100,122,33,4,5,6])
x

270

## Range Function

In [45]:
#Range Fucntion
x = range(100)
x

range(0, 100)

## Tuple

In [4]:
bin_color = ('Red','Green','Blue','Yellow')
bin_color

('Red', 'Green', 'Blue', 'Yellow')

In [5]:
bin_color[1]

'Green'

In [6]:
bin_color[2:]

('Blue', 'Yellow')

In [14]:
a = (1,2,3,4,5,(100,200,300,400,500))
a

(1, 2, 3, 4, 5, (100, 200, 300, 400, 500))

## Dictionary

In [20]:
bin_color = {
    "manaul_copy" : "Yellow",
    "approved_copy" : "Green",
    "refused_color" : "Red"
}
bin_color

{'manaul_copy': 'Yellow', 'approved_copy': 'Green', 'refused_color': 'Red'}

In [22]:
bin_color.get('approved_copy')

'Green'

In [24]:
bin_color['approved_copy']

'Green'

In [26]:
bin_color['approved_copy']='Purple'
bin_color

{'manaul_copy': 'Yellow', 'approved_copy': 'Purple', 'refused_color': 'Red'}

## Sets

In [30]:
green = {'grass','leaves','leaf','leaf'}
print(green)

{'leaves', 'leaf', 'grass'}


In [31]:
yellow = {'dandelions','fire','fire_hydrant','leaves'}
red = {'rose','fire','fire_hydrant','blood'}

In [34]:
yellow | red

{'blood', 'dandelions', 'fire', 'fire_hydrant', 'leaves', 'rose'}

In [33]:
yellow & red

{'fire', 'fire_hydrant'}

## DataFrames

In [66]:
import pandas as pd
import numpy as np

In [50]:
df = pd.DataFrame([
    ['1','Danial',22,True],
    ['2','Biggooo',24,False],
    ['3','Owais',20,True],
    ['4','Owsy',21,False]
])
df.columns = ['id','name','age','decision']
df

id     name  age  decision
0  1   Danial   22      True
1  2  Biggooo   24     False
2  3    Owais   20      True
3  4     Owsy   21     False

In [51]:
#Column Selection
df[['name','age']]

name  age
0   Danial   22
1  Biggooo   24
2    Owais   20
3     Owsy   21

In [52]:
df.iloc[:,3]

0     True
1    False
2     True
3    False
Name: decision, dtype: bool

In [53]:
# Row Selection
df.iloc[1:3,:]

id     name  age  decision
1  2  Biggooo   24     False
2  3    Owais   20      True

In [59]:
df[(df.age > 20) & (df.age < 25)]

id     name  age  decision
0  1   Danial   22      True
1  2  Biggooo   24     False
3  4     Owsy   21     False

In [64]:
df[(df.age < 24) & (df.decision == True)]

id    name  age  decision
0  1  Danial   22      True
2  3   Owais   20      True

## Matrix

In [69]:
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)
print(type(myMatrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [70]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])